FROM node:22-alpine

RUN apk add --no-cache git \
 && npm install -g opencode-ai \
 && mkdir -p /home/node/.config/opencode

COPY ./dot_config/opencode /home/node/.config/opencode

WORKDIR /workspace

ENTRYPOINT ["opencode"]
CMD []
