dependencies:
  - role: Comcast.sdkman
    sdkman_user: januson
    sdkman_group: januson
    sdkman_auto_answer: true
    sdkman_update: true
    sdkman_install_packages:
      - { candidate: java, version: 16.0.1-open }
      - { candidate: java, version: 8.0.292-open }
      - { candidate: gradle, version: 7.1.1 }
      - { candidate: maven, version: 3.8.1 }
    sdkman_defaults:
      gradle: 7.1.1
      maven: 3.8.1
      java: 8.0.292-open
    sdkman_flush_caches_before:
      - temp
    sdkman_flush_caches_after:
      - archives
      - broadcast
      - candidates
      - temp
    sdkman_offline_mode: false
    sdkman_update_alternatives:
      - candidate: java
        name: java
        link: /usr/bin/java
      - candidate: java
        name: javac
        link: /usr/bin/javac
