---
- name: Install CLI tools
  dnf:
    name:
      # network utilization
      - bandwhich
      # cat clone
      - bat
      # git and diff viewer
      - delta
      # du alternative
      - dust
      # find alternative
      - fd
      # generates regexes from examples
      - grex
      # benchmarking
      - hyperfine
      # ls alternative
      - lsd
      # ps alternative
      - procs
      # grep alternative
      - ripgrep
      # search and replace
      - sd
      # tldr alternative
      - tealdeer
      # top alternative
      - ytop
      # cd alternative
      - zoxide
    state: latest

- name: Check if sdkman is installed
  shell: sdk list java
  register: sdkman
  check_mode: false
  changed_when: false
  failed_when: sdkman.rc != 0 and result.rc != 127

- name: Install sdkman
  shell: |
    curl -s "https://get.sdkman.io" | bash
  when: "'command not found' in sdkman.stdout"

- name: Install JVM tools
  shell: |
    sdk install java
    sdk install gradle
    sdk install maven
  when: "'command not found' in sdkman.stdout"
