---
- name: Install zsh
  dnf:
    name:
      - zsh
    state: latest
  become: true

- name: Clone Prezto
  git:
    repo: git@github.com:sorin-ionescu/prezto.git
    dest: ~/.prezto
    force: no
    recursive: yes

- name: Link in Prezto files
  copy:
    state: present
    src: "{{ item.src }}"
    dest: "{{ item.dst }}{{ item.src }}"
    mode: 0664
    force: yes
  loop:
    - {src: "zpreztorc", dst: "~/.zprezto/runcoms/"}
    - {src: "zshrc", dst: "~/.zprezto/runcoms/"}
    - {src: "aliases", dst: "~/."}

- name: Link in Prezto files
  copy:
    state: link
    src: "{{ item }}"
    dest: "~/.zprezto/runcoms/{{ item }}"
    mode: 0664
    force: yes
  loop:
    - zpreztorc
    - zshrc
